FROM ubuntu:14.04

# Install Node...
RUN apt-get update

# install npm
RUN apt-get install -y -qq npm
RUN ln -s /usr/bin/nodejs /usr/bin/node

# install bower
RUN npm install --global bower

# Install app and dependencies into /src
RUN cd /src; npm install
RUN cd /src; bower install

EXPOSE 8080

CMD cd /src && npm start